package org.total.postgre.entity.enums;

/**
 * @author kostya
 */

public enum TournamentCode {
    ENG_PREM_LEAGUE, ENG_CHAMPIONSHIP, ITA_SERIA_A, ITA_SERIA_B, ITA_SERIA_C, DEU_BUNDESLIGA_1, DEU_BUNDESLIGA_2, DEU_BUNDESLIGA_3, ESP_PRIMERA, ESP_SEGUNDA, FRA_LIGUE_1, FRA_LIGUE_2, CHAMPIONS_LEAGUE, NLD_EREDIVISIE, PRT_PRIMEIRA_LIGA
}